[build]
builder = "nixpacks"
watchPatterns = ["backend/**", "docker-compose.yml"]

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/api/latest"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[nixpacks]
nodeVersion = "18" 