[phases.setup]
nixPkgs = ["nodejs", "npm"]

[variables]
NODE_VERSION = "18"

[phases.build]
cmds = ["cd backend && npm install && npm run prisma:generate && npm run build"]

[start]
cmd = "cd backend && npm start" 